### ISSUE TITLE
Some parameters to upgrade - Not immediate

### ISSUE THREAD

**Issue by bernard-kav** [llooker/transcriber#6]
Please feel free to add any that may pop up over time:

1. In the `Models` section, the last check: 
```
View files should follow standard naming conventions. When there are large number of Views, use model_name_view_name or another prefix to co-locate Views in the navigation tree.
```

Is not applicable now with folders.

**Comment by drewgillson** [comment]
Hi Bernard, please go ahead and edit the associated Guru card to solve this: https://app.getguru.com/card/iGB6RkXT/Models
